server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        if ($request_filename ~* \.(html)$ ) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }

    location ~* \.(?:js|css|webp|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|otf|eot)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
